"""update PlayerModel

Revision ID: a86689172332
Revises: 78f19499454a
Create Date: 2024-11-19 06:44:55.364234

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a86689172332"
down_revision: Union[str, None] = "78f19499454a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "players", sa.Column("round", sa.Integer(), server_default="1", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "round")
    # ### end Alembic commands ###
