name: Check homework

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install ruff
        run: pip install ruff==0.4.2
      - run: ruff format --check && ruff check --no-fix

  docker_build_and_publish:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push app Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/photo-contest-bot-server:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/photo-contest-bot-server:latest

      - name: Build and push db Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/postgres:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/postgres:latest
